### ISSUE TITLE
Error during conversion to coreML

### ISSUE THREAD

**Issue by QueryType** [argmaxinc/DiffusionKit#13]
Facing the following issue during conversion.
Mac M2 mini, 24GB

```
 % python -m python.src.diffusionkit.tests.torch2coreml.test_mmdit --sd3-ckpt-path /Volumes/d/apps/sdxl/stable-diffusion-webui/models/Stable-diffusion/3/sd3_medium.safetensors --model-version 2b -o mlpackage --latent-size 64
scikit-learn version 1.5.1 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.
Torch version 2.4.0 has not been tested with coremltools. You may run into unexpected errors. Torch 2.2.0 is the most recent version that has been tested.
<frozen runpy>:128: RuntimeWarning: 'python.src.diffusionkit.tests.torch2coreml.test_mmdit' found in sys.modules after import of package 'python.src.diffusionkit.tests.torch2coreml', but prior to execution of 'python.src.diffusionkit.tests.torch2coreml.test_mmdit'; this may result in unpredictable behaviour
INFO:__main__:Initializing SD3 model
INFO:__main__:Initialized.
INFO:__main__:Loading SD3 model checkpoint from /Volumes/d/apps/sdxl/stable-diffusion-webui/models/Stable-diffusion/3/sd3_medium.safetensors
INFO:diffusionkit.torch.model_io:Loading state_dict into nn.Module with  635 parameter tensors totaling 2084877376 parameters from /Volumes/d/apps/sdxl/stable-diffusion-webui/models/Stable-diffusion/3/sd3_medium.safetensors
INFO:diffusionkit.torch.model_io:Loaded state dict with 635 tensors totaling 2084877376 parameters
INFO:__main__:Loaded.
/Volumes/d/code/aiml/DiffusionKit/python/src/diffusionkit/torch/mmdit.py:206: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  -torch.log(torch.tensor(self.config.max_period).to(t.dtype))
/Volumes/d/code/aiml/DiffusionKit/python/src/diffusionkit/torch/mmdit.py:160: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert h <= self.max_hw and w <= self.max_hw
E
======================================================================
ERROR: setUpClass (__main__.TestSD3MMDiT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/d/code/aiml/DiffusionKit/python/src/diffusionkit/tests/torch2coreml/test_mmdit.py", line 93, in setUpClass
    super().setUpClass()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/diffusionkit/lib/python3.11/site-packages/argmaxtools/test_utils.py", line 56, in setUpClass
    cls.test_coreml_model = _create_coreml_model(
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/diffusionkit/lib/python3.11/site-packages/argmaxtools/test_utils.py", line 414, in _create_coreml_model
    inputs=[
           ^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/diffusionkit/lib/python3.11/site-packages/argmaxtools/test_utils.py", line 415, in <listcomp>
    ct.TensorType(k, shape=v.shape, dtype=v.dtype)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/diffusionkit/lib/python3.11/site-packages/coremltools/converters/mil/input_types.py", line 229, in __init__
    self.dtype = numpy_type_to_builtin_type(dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/diffusionkit/lib/python3.11/site-packages/coremltools/converters/mil/mil/types/type_mapping.py", line 363, in numpy_type_to_builtin_type
    if np.issubclass_(type(nptype), np.dtype):
       ^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/diffusionkit/lib/python3.11/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.issubclass_` was removed in the NumPy 2.0 release. Use `issubclass` builtin instead.

----------------------------------------------------------------------
Ran 0 tests in 28.835s

FAILED (errors=1)

```
Torch version 2.4.0 has not been tested with coremltools. You may run into unexpected errors. Torch 2.2.0 is the most recent version that has been tested. If this is the issue, then we must downgrade to 2.2.0. But I guess when we are doing pip install of the repo, it is installing 2.4.0 (latest one). Could this be? Even I guess NumPy....

**Comment by atiorh** [comment]
This is a known issue with `numpy>=2.0` + `coremltools`. Quick workaround: `pip install numpy==1.26.4`

**Comment by QueryType** [comment]
Thanks this worked!
