### ISSUE TITLE
Image resolution crash

### ISSUE THREAD

**Issue by TuiKiken** [argmaxinc/DiffusionKit#29]
I get an error if the image resolution is set.

``` bash
(diffusionkit_3.10) ~/Projects/DiffusionKit (flux ✔) diffusionkit-cli --prompt "a photo of a cat" --output-path test_flux.png --height 592 --width 840 --step 4
WARNING:diffusionkit.mlx.scripts.generate_images:Disabling CFG for FLUX.1-schnell model.
/opt/homebrew/Caskroom/miniconda/base/envs/diffusionkit_3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
INFO:diffusionkit.mlx.scripts.generate_images:Output image resolution will be 595x842
INFO:diffusionkit.mlx:Pre text encoding peak memory: 0.0GB
INFO:diffusionkit.mlx:Pre text encoding active memory: 0.0GB
INFO:diffusionkit.mlx:Post text encoding peak memory: 2.526GB
INFO:diffusionkit.mlx:Post text encoding active memory: 0.476GB
INFO:diffusionkit.mlx:Text encoding time: 1.874s
INFO:diffusionkit.mlx:Pre denoise peak memory: 0.0GB
INFO:diffusionkit.mlx:Pre denoise active memory: 0.002GB
INFO:diffusionkit.mlx:Seed: 1725410986
  0%|                                                                                                                                                                                           | 0/4 [00:00<?, ?it/s]
INFO:diffusionkit.mlx.mmdit:Cached modulation_params for timesteps=array([1000, 752, 500, 250, 0], dtype=bfloat16)
INFO:diffusionkit.mlx.mmdit:Cached modulation_params will reduce peak memory by 6.5 GB
  0%|                                                                                                                                                                                           | 0/4 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/diffusionkit_3.10/bin/diffusionkit-cli", line 33, in <module>
    sys.exit(load_entry_point('diffusionkit', 'console_scripts', 'diffusionkit-cli')())
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/scripts/generate_images.py", line 163, in cli
    image, _ = sd.generate_image(
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/__init__.py", line 376, in generate_image
    latents, iter_time = self.denoise_latents(
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/__init__.py", line 249, in denoise_latents
    latent, iter_time = sample_euler(
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/__init__.py", line 725, in sample_euler
    denoised = model(x, timesteps[i], sigmas[i], **extra_args)
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/__init__.py", line 661, in __call__
    mmdit_output = self.model.mmdit(**mmdit_input)
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/mmdit.py", line 193, in __call__
    latent_image_embeddings = self.x_embedder(latent_image_embeddings)
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/mmdit.py", line 288, in __call__
    x.reshape(b, h_latent // p, p, w_latent // p, p, c)
ValueError: [reshape] Cannot reshape array of size 124320 into shape (1,37,2,52,2,16).
```

**Comment by atiorh** [comment]
Hi @TuiKiken, the resolution should be divisible by 16 for FLUX. 840/16=52.5. @arda-argmax could you please add an argument check for divisibility?

**Comment by TuiKiken** [comment]
@atiorh Multiples of 16 work great. I think validating arguments is a great idea. Thank you.
