### ISSUE TITLE
Error in the script clip.py

### ISSUE THREAD

**Issue by TuiKiken** [argmaxinc/DiffusionKit#30]
Are there any restrictions on the length of the promt?

``` bash
(diffusionkit_3.10) ~/Projects/DiffusionKit (flux ✔) diffusionkit-cli --height 592 --width 832 --step 4 --output-path images/test_flux9.png --prompt "Create a detailed black and white line drawing suitable for a 9-year-old's coloring book. The central figure is a rabbit wearing a space suit, complete with a clear bubble helmet. The rabbit is standing on the surface of an alien planet with a starry sky above. Surrounding the rabbit are various alien plants with unusual shapes - some look like spirals, others like giant leaves or tentacles. In the background, include two or three curious alien creatures peeking out from behind rocks or plants. One alien could have multiple eyes, another could have antennae. Add craters and strange rock formations to the planet's surface. Include a distant planet or moon in the sky. The level of detail should be moderate, with clear lines and some intricate patterns on the space suit and alien flora, providing an engaging but not overly complex coloring experience for a 9-year-old."
WARNING:diffusionkit.mlx.scripts.generate_images:Disabling CFG for FLUX.1-schnell model.
/opt/homebrew/Caskroom/miniconda/base/envs/diffusionkit_3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
INFO:diffusionkit.mlx.scripts.generate_images:Output image resolution will be 592x832
INFO:diffusionkit.mlx:Pre text encoding peak memory: 0.0GB
INFO:diffusionkit.mlx:Pre text encoding active memory: 0.0GB
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/diffusionkit_3.10/bin/diffusionkit-cli", line 33, in <module>
    sys.exit(load_entry_point('diffusionkit', 'console_scripts', 'diffusionkit-cli')())
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/scripts/generate_images.py", line 163, in cli
    image, _ = sd.generate_image(
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/__init__.py", line 310, in generate_image
    conditioning, pooled_conditioning = self.encode_text(
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/__init__.py", line 605, in encode_text
    conditioning_l = self.clip_l(tokens_l[[0], :])  # Ignore negative text
  File "/Users/valentin/Projects/DiffusionKit/python/src/diffusionkit/mlx/clip.py", line 98, in __call__
    x = x + self.position_embedding.weight[:N]
ValueError: Shapes (1,177,768) and (77,768) cannot be broadcast.
```

**Comment by arda-argmax** [comment]
You might be using an older version of diffusionkit. Can you update it using this command:
```
pip install diffusionkit -U
```

**Comment by TuiKiken** [comment]
Thank you
