### ISSUE TITLE
Runtime error with argmaxtools

### ISSUE THREAD

**Issue by ngaloppo** [argmaxinc/DiffusionKit#36]
Submitting here, since I can't find the `argmaxtools` repo anymore, and I'm getting the error while using DiffusionKit. 

Getting the following error after generation completes (but before the output image gets generated):

```
Traceback (most recent call last):
  File "/Users/ngaloppo/miniforge3/envs/diffusionkit/bin/diffusionkit-cli", line 33, in <module>
    sys.exit(load_entry_point('diffusionkit', 'console_scripts', 'diffusionkit-cli')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ngaloppo/code/DiffusionKit/python/src/diffusionkit/mlx/scripts/generate_images.py", line 170, in cli
    image, _ = sd.generate_image(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/ngaloppo/code/DiffusionKit/python/src/diffusionkit/mlx/__init__.py", line 512, in generate_image
    pprint(ic.os_spec())
           ^^^^^^^^^^^^
  File "/Users/ngaloppo/miniforge3/envs/diffusionkit/lib/python3.11/site-packages/argmaxtools/test_utils.py", line 383, in os_spec
    os_type, os_version, os_build_number = [
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)
```

**Comment by atiorh** [comment]
Could you please share the output of `sw_vers` from your terminal?

**Comment by ngaloppo** [comment]
Unfortunately, I can't. What I can say is that it has more than three lines of output.

**Comment by ZachNagengast** [comment]
@ngaloppo Are the first three in the correct order as `os_type, os_version, os_build_number`? We can add a variable to accept the remaining values perhaps without crashing.

**Comment by ngaloppo** [comment]
Yes, that’s correct!
